version: '3'
services:
  web:
    container_name: "web"
    build:
        context: "./php56"
        dockerfile: "Dockerfile"
    ports:
        - "8080:80"
    volumes:
        - ~/docker_dev/sampleapp:/var/www/html
    links:
        - "db:db"
  db:
    #dockerfileなくてもpullするだけだったら下記のコメントでもOK
    #image: "mysql:latest"
    container_name: "db"
    build:
        context: "./mysql"
        dockerfile: "Dockerfile"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
