version: '3'
services:
  web:
    container_name: "web"
    build:
        context: "./php56"
        dockerfile: "Dockerfile"
    ports:
        - "8080:80"
    volumes:
        - ./public_html/:/var/www/html
    links:
        - "db:db"
  db:
    #dockerfileなくてもpullするだけだったら下記のコメントでもOK
    #image: "mysql:latest"
    container_name: "db"
    build:
        context: "./mysql"
        dockerfile: "Dockerfile"
#    volumes:
#        # 初期データを投入するSQLが格納されているdir
#        - ./mysql/mysql_init:/docker-entrypoint-initdb.d
#        # 永続化するときにマウントするdir
#        - ./mysql/mysql_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "root"
