version: '3'
services:
  web:
    build:
        context: ./php56
        dockerfile: Dockerfile
    ports:
        - "8080:80"
    links:
        - db
  db:
    #dockerfileなくてもpullするだけだったら下記のコメントでもOK
    #image: "mysql:latest"
    build:
        context: ./mysql
        dockerfile: Dockerfile
    environment:
        MYSQL_ROOT_PASSWORD: root
