version: '3'
services:
  db:
    #dockerfileなくてもpullするだけだったら下記のコメントでもOK
    #image: "mysql:latest"
    container_name: "db"
    build:
        context: "./mysql"
        dockerfile: "Dockerfile"
    volumes:
        # 初期データを投入するSQLが格納されているdir
        - ./mysql/init.sql:/docker-entrypoint-initdb.d/
#        # 永続化するときにマウントするdir
#        - ./mysql/mysql_data:/var/lib/mysql
